name: map_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  firebase_core: ^2.25.4
  flutter:
    sdk: flutter
  # open_street_map_search_and_pick: ^0.1.1
  url_launcher: ^6.2.4
  animate_do: ^3.1.2
  flutter_svg: ^2.0.9
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_rating_bar: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
