// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdGFs_lWeYJ87LgMz-YDY1MD210SlYnls',
    appId: '1:519358647739:web:c4409770e6a05796ddc89e',
    messagingSenderId: '519358647739',
    projectId: 'recommendations-ced03',
    authDomain: 'recommendations-ced03.firebaseapp.com',
    storageBucket: 'recommendations-ced03.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJb2d-C713KaBkJ7ztR9xDbQyl5Vrl-bg',
    appId: '1:519358647739:android:e9d2c7500e67256cddc89e',
    messagingSenderId: '519358647739',
    projectId: 'recommendations-ced03',
    storageBucket: 'recommendations-ced03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-yLmfSfrrUmN0xRfW6gjfvzApOQExaaQ',
    appId: '1:519358647739:ios:00e2d9cd5dbc64d3ddc89e',
    messagingSenderId: '519358647739',
    projectId: 'recommendations-ced03',
    storageBucket: 'recommendations-ced03.appspot.com',
    iosBundleId: 'com.example.mapTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-yLmfSfrrUmN0xRfW6gjfvzApOQExaaQ',
    appId: '1:519358647739:ios:a5a8a484df17f7dbddc89e',
    messagingSenderId: '519358647739',
    projectId: 'recommendations-ced03',
    storageBucket: 'recommendations-ced03.appspot.com',
    iosBundleId: 'com.example.mapTest.RunnerTests',
  );
}
